#!/usr/bin/env node
/**
 * Generate .env file with service URLs
 *
 * Usage: space run env [output-file]
 */

const fs = require('fs');

// Read context from stdin
let data = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', chunk => data += chunk);
process.stdin.on('end', () => {
  const context = JSON.parse(data);
  const outputFile = context.args[0] || '.env.local';

  const lines = [
    `# Generated by space run env`,
    `# ${new Date().toISOString()}`,
    ``,
    `SPACE_PROJECT=${context.project_name}`,
    `SPACE_HASH=${context.hash}`,
    ``
  ];

  for (const [name, svc] of Object.entries(context.services)) {
    const envName = name.toUpperCase().replace(/-/g, '_');
    lines.push(`${envName}_URL=${svc.url}`);
    lines.push(`${envName}_HOST=${svc.dns_name}`);
    lines.push(`${envName}_PORT=${svc.internal_port}`);
    lines.push(``);
  }

  fs.writeFileSync(outputFile, lines.join('\n'));
  console.log(`Generated ${outputFile}`);
});
