#!/bin/bash
# .space/hooks/post-up.d/10-vite-env.sh
# Auto-generates Vite environment file with space.local URLs

set -e

# Read JSON context from stdin
CONTEXT=$(cat)

# Check if this is a Vite project
if [[ ! -f "vite.config.ts" ]] && [[ ! -f "vite.config.js" ]]; then
  exit 0
fi

echo "🎨 Configuring Vite environment..."

# Check if jq is available
if ! command -v jq &> /dev/null; then
  echo "   ⚠️  jq not found, using environment variables"

  # Fallback to environment variables
  if [[ -n "$SPACE_SERVICE_API_SERVER_DNS_NAME" ]]; then
    cat > .env.development.local << EOF
# Auto-generated by space hooks - $(date)
VITE_API_BASE_URL=http://${SPACE_SERVICE_API_SERVER_DNS_NAME}:${SPACE_SERVICE_API_SERVER_PORT:-6060}
EOF
    echo "   ✅ Generated .env.development.local"
  fi
  exit 0
fi

# Extract service info using jq
API_HOST=$(echo "$CONTEXT" | jq -r '.services["api-server"].dns_name // empty')
API_PORT=$(echo "$CONTEXT" | jq -r '.services["api-server"].internal_port // empty')
APP_HOST=$(echo "$CONTEXT" | jq -r '.services["app"].dns_name // empty')
APP_PORT=$(echo "$CONTEXT" | jq -r '.services["app"].internal_port // empty')

# Generate .env.development.local
{
  echo "# Auto-generated by space hooks - $(date)"

  if [[ -n "$API_HOST" ]] && [[ -n "$API_PORT" ]]; then
    echo "VITE_API_BASE_URL=http://${API_HOST}:${API_PORT}"
  fi

  if [[ -n "$APP_HOST" ]] && [[ -n "$APP_PORT" ]]; then
    echo "VITE_APP_BASE_URL=http://${APP_HOST}:${APP_PORT}"
  fi
} > .env.development.local

echo "   ✅ Generated .env.development.local"
cat .env.development.local | sed 's/^/      /'
